### ISSUE TITLE
Error at index.js:105:17

### ISSUE THREAD

**Issue by iromise** [xfslove/alfred-google-translate#12]
I just input `tr hello`, it tells me to press command+L to show more details error

Error at /usr/local/lib/node_modules/alfred-google-translate/node_modules/china-google-translate-api/index.js:105:17 at `<anonymous>`

My nodejs version is
```shell
➜  china-google-translate-api npm --version
5.6.0
```

**Comment by xfslove** [comment]
@iromise thx for report, i'll take a look at this problem!

**Comment by xfslove** [comment]
@lingyv 能看一下这个异常的问题不

**Comment by lingyv** [comment]
@iromise 这个错误是在请求 URL 时发生的, 我看不到错误信息, 你在命令行执行下面命令看看错误信息是什么:
```
curl https://translate.google.cn/translate_a/single?client=t&sl=auto&tl=zh-cn&hl=zh-cn&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=hello&tk=970599.543581
```

**Comment by iromise** [comment]
here is the result, @lingyv 
```shell
➜  /tmp curl https://translate.google.cn/translate_a/single\?client\=t\&sl\=auto\&tl\=zh-cn\&hl\=zh-cn\&dt\=at\&dt\=bd\&dt\=ex\&dt\=ld\&dt\=md\&dt\=qca\&dt\=rw\&dt\=rm\&dt\=ss\&dt\=t\&ie\=UTF-8\&oe\=UTF-8\&otf\=1\&ssel\=0\&tsel\=0\&kc\=7\&q\=hello\&tk\=970599.543581

<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 403 (Forbidden)!!1</title><style>*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><a href=//www.google.com/><span id=logo aria-label=Google></span></a><p><b>403.</b> <ins>That’s an error.</ins><p>Your client does not have permission to get URL <code>/translate_a/single?client=t&amp;sl=auto&amp;tl=zh-cn&amp;hl=zh-cn&amp;dt=at&amp;dt=bd&amp;dt=ex&amp;dt=ld&amp;dt=md&amp;dt=qca&amp;dt=rw&amp;dt=rm&amp;dt=ss&amp;dt=t&amp;ie=UTF-8&amp;oe=UTF-8&amp;otf=1&amp;ssel=0&amp;tsel=0&amp;kc=7&amp;q=hello&amp;tk=970599.543581</code> from this server.  (Client IP address: 61.148.243.12)<br><br>


  <ins>That’s all we know.</ins>
```

**Comment by iromise** [comment]
I can not access translate.google.com, but .cn is ok, here is the info

```shell
➜  ~ curl https://translate.google.com/translate_a/single\?client\=t\&sl\=auto\&tl\=zh-cn\&hl\=zh-cn\&dt\=at\&dt\=bd\&dt\=ex\&dt\=ld\&dt\=md\&dt\=qca\&dt\=rw\&dt\=rm\&dt\=ss\&dt\=t\&ie\=UTF-8\&oe\=UTF-8\&otf\=1\&ssel\=0\&tsel\=0\&kc\=7\&q\=hello\&tk\=970599.543581




^C
➜  ~ ping translate.google.cn
PING translate.google.cn (203.208.40.119): 56 data bytes
64 bytes from 203.208.40.119: icmp_seq=0 ttl=112 time=60.784 ms
64 bytes from 203.208.40.119: icmp_seq=1 ttl=112 time=50.756 ms
➜  ~ ping translate.google.com
PING www3-china.l.google.com (74.125.204.139): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
```

**Comment by xfslove** [comment]
@iromise ummmmm... I'm not sure why you had get message like "Your client does not have permission to get URL." . @lingyv 'll working on this.
but maybe It's not a bug, take a look at [this description](https://github.com/googleapis/google-api-go-client/issues/155).

**Comment by martint028** [comment]
> error information
```json
[2018-09-25 17:44:11][ERROR: input.scriptfilter] Code 1: {
	"items": [
		{
			"title": "Error\n    at /usr/local/lib/node_modules/alfred-google-translate/node_modules/china-google-translate-api/index.js:105:17\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nError\n    at /usr/local/lib/node_modules/alfred-google-translate/node_modules/china-google-translate-api/index.js:105:17\n```\n\n-\nGoogle Translate 1.1.0\nAlfred 3.7\ndarwin x64 18.0.0",
				"largetype": "Error\n    at /usr/local/lib/node_modules/alfred-google-translate/node_modules/china-google-translate-api/index.js:105:17"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
[2018-09-25 17:44:11][input.scriptfilter] Script with argument 'kate' finished
[2018-09-25 17:44:11][ERROR: input.scriptfilter] Code 1: {
	"items": [
		{
			"title": "Error\n    at /usr/local/lib/node_modules/alfred-google-translate/node_modules/china-google-translate-api/index.js:105:17\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nError\n    at /usr/local/lib/node_modules/alfred-google-translate/node_modules/china-google-translate-api/index.js:105:17\n```\n\n-\nGoogle Translate 1.1.0\nAlfred 3.7\ndarwin x64 18.0.0",
				"largetype": "Error\n    at /usr/local/lib/node_modules/alfred-google-translate/node_modules/china-google-translate-api/index.js:105:17"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
```

**Comment by lingyv** [comment]
@iromise i don't know why you don't have permission, maybe you can change computer or network and then run that command again.

**Comment by lingyv** [comment]
@martint028 you got a 403 error ?

**Comment by martint028** [comment]
@lingyv yes

**Comment by sailor103** [comment]
same problem, if anyone can help me? 

 `Error at /usr/local/lib/node_modules/alfred-google-translate/node_modules/china-google-translate-api/index.js:105:17 at <anonymous>`

**Comment by lingyv** [comment]
@sailor103 @martint028 if you can access `translate.google.com`, try this command:
```
curl https://translate.google.com/translate_a/single?client=t&sl=auto&tl=zh-cn&hl=zh-cn&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=hello&tk=970599.543581
```

**Comment by martint028** [comment]
@lingyv After entering this command, there is still the same error

**Comment by lingyv** [comment]
When is the workflow installed?

**Comment by martint028** [comment]
After upgrading to the official version of Mojave

**Comment by lingyv** [comment]
`china-google-translate-api` is done by modifying the code of [google-translate-api
](https://github.com/matheuss/google-translate-api). 
can you follow the `README.md` of [google-translate-api
](https://github.com/matheuss/google-translate-api) and try it ?

**Comment by xfslove** [comment]
[related issue](https://github.com/matheuss/google-translate-api/issues/70)

**Comment by Astraeux** [comment]
我也遇到了这个问题，curl translate.google.com 或 translate.google.cn 都产生相同错误

**Comment by piccy** [comment]
Maybe the problem is missing User Agent:

``` bash
curl -A "Mozilla/5.0" "https://translate.google.cn/translate_a/single?client=t&sl=auto&tl=zh-cn&hl=zh-cn&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=hello&tk=970599.543581"
```
Return is OK.

``` bash
curl "https://translate.google.cn/translate_a/single?client=t&sl=auto&tl=zh-cn&hl=zh-cn&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=hello&tk=970599.543581"
```
Return is 403.

**Comment by xfslove** [comment]
@sailor103 @martint028 @iromise @Astraeux Please have a try.

**Comment by Astraeux** [comment]
> @sailor103 @martint028 @iromise @Astraeux Please have a try.

curl with User Agent is OK.

**Comment by piccy** [comment]
@xfslove 
@Astraeux 

``` bash
vi /usr/local/Cellar/node@6/6.13.0/lib/node_modules/alfred-google-translate/node_modules/china-google-translate-api/index.js
```
chage line 105 to :
``` js
        return got(url, {headers: { 'user-agent': 'Mozilla/5.0' }}).then(function (res) {
```

**Comment by xfslove** [comment]
if it's works, @lingyv 'll update translate-api packages.

**Comment by lingyv** [comment]
ok, i get it, thank you all. 
I have upgraded the version from 2.3.0 to 2.3.1.

**Comment by Astraeux** [comment]
> @xfslove
> @Astraeux
> 
> ```shell
> vi /usr/local/Cellar/node@6/6.13.0/lib/node_modules/alfred-google-translate/node_modules/china-google-translate-api/index.js
> ```
> 
> chage line 105 to :
> 
> ```js
>         return got(url, {headers: { 'user-agent': 'Mozilla/5.0' }}).then(function (res) {
> ```

line 105:
```
            e = new Error();
```

line 52:
```
        return got(url).then(function (res) {
```

I try change line 52 to:
```
        return got(url, {headers: { 'user-agent': 'Mozilla/5.0' }}).then(function (res) {
```

But it does't work.

````
Error
    at /usr/local/lib/node_modules/alfred-google-translate/node_modules/china-google-translate-api/index.js:105:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

-
Google Translate 1.1.0
Alfred 3.7
darwin x64 17.5.0`

**Comment by likecreep** [comment]
我也遇到这个问题。 试过添加了user-agent也没有用。 是不是可能china-google-translate-token 这个依赖产生的tk没有用？

**Comment by xfslove** [comment]
> 这个问题解决了吗？？

这个问题目前看来应该是api限制的原因，目前还没有好的办法解决

**Comment by Astraeux** [comment]
> > 这个问题解决了吗？？
> 
> 这个问题目前看来应该是api限制的原因，目前还没有好的办法解决

为什么我执行curl加上user agent可以成功，但代码加上user agent仍然失败？

**Comment by xfslove** [comment]
像 @likecreep 说的可能生成的token没用

**Comment by sailor103** [comment]
mac 上最好用的翻译助手就这么不能用了吗？现在每次tr一下，然后翻译不了。。

**Comment by lingyv** [comment]
look at this [issues](https://github.com/matheuss/google-translate-api/issues/79), and try [this way](https://github.com/vitalets/google-translate-token/commit/0b2bd0d8cd63cc4e8a191c359d683511d46556a6)

**Comment by Astraeux** [comment]
> look at this [issues](https://github.com/matheuss/google-translate-api/issues/79), and try [this way](https://github.com/vitalets/google-translate-token/commit/0b2bd0d8cd63cc4e8a191c359d683511d46556a6)

This way is worked, don't need to change user agent.

**Comment by lingyv** [comment]
ok, thank you, i'll upgrade later

**Comment by lingyv** [comment]
everybody, i have pushed the update, please upgrade your workflow and try again.
