### ISSUE TITLE
npm 安装失败

### ISSUE THREAD

**Issue by PTDog** [xfslove/alfred-google-translate#13]
系统10.14
```
apple$ sudo npm install -g alfred-google-translate

> alfred-google-translate@1.1.0 postinstall /usr/local/lib/node_modules/alfred-google-translate
> alfy-init

{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/apple/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-google-translate/node_modules/resolve-alfred-prefs/index.js:15:10)
    at <anonymous>

    at Promise.all.then.arr (/usr/local/lib/node_modules/alfred-google-translate/node_modules/execa/index.js:201:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Alfred preferences not found at location /Users/apple/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-google-translate/node_modules/resolve-alfred-prefs/index.js:15:10)\n    at <anonymous>\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-google-translate@1.1.0 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alfred-google-translate@1.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2018-10-17T02_45_21_697Z-debug.log
`````

**Comment by xfslove** [comment]
@PTDog 你Alfred是不是丢失配置了，看错误信息`com.runningwithcrayons.Alfred-Preferences-3.plist`是找不到

**Comment by PTDog** [comment]
我手动去这个目录找了，这个文件是有的。alfred版本3.7

**Comment by xfslove** [comment]
([试一下](https://www.alfredapp.com/help/troubleshooting/preferences/))
