### ISSUE TITLE
Workflow stopped working after the new update

### ISSUE THREAD

**Issue by Aracki** [xfslove/alfred-google-translate#73]
I'm always seeing the following thing:
![image](https://user-images.githubusercontent.com/6129986/98106173-5cc25000-1e99-11eb-8531-c51641d24de6.png)

Even after I run the `npm install` command, it's the same and it doesn't work at all. Any ideas...?

**Comment by xfslove** [comment]
which version installed on your local now. ` npm ls -g alfred-google-translate`

**Comment by Aracki** [comment]
`└── alfred-google-translate@2.0.9`

**Comment by xfslove** [comment]
it's weird, could you have a try to reinstall that manually? `npm uninstall -g alfred-google-translate` and then `npm install -g alfred-google-translate`.

**Comment by Aracki** [comment]
Ok, now I don't see the "Update available..." message, but it still doesn't translate a thing.

**Comment by xfslove** [comment]
<img width="855" alt="1" src="https://user-images.githubusercontent.com/7803346/98313195-45f13a00-200e-11eb-92d1-23959654cc55.png">
please toggle the debug mode. and post the snapshot of Logging. 
and please make sure you can access the translate.google.com first.

**Comment by Aracki** [comment]
Yes, I can access translate.google.com

Logs:
```
(node:7340) UnhandledPromiseRejectionWarning: /usr/local/lib/node_modules/alfred-google-translate/node_modules/read-pkg-up/node_modules/parse-json/index.js:1
Error: Cannot find module 'json-parse-better-errors'
Require stack:
- /usr/local/lib/node_modules/alfred-google-translate/node_modules/read-pkg-up/node_modules/parse-json/index.js
- /usr/local/lib/node_modules/alfred-google-translate/node_modules/read-pkg-up/node_modules/read-pkg/index.js
- /usr/local/lib/node_modules/alfred-google-translate/node_modules/read-pkg-up/index.js
- /usr/local/lib/node_modules/alfred-google-translate/node_modules/alfy/lib/update-notification.js
- /usr/local/lib/node_modules/alfred-google-translate/node_modules/alfy/index.js
- /usr/local/lib/node_modules/alfred-google-translate/index.js
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-google-translate/node_modules/read-pkg-up/node_modules/parse-json/index.js:3:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
(node:7340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7340) UnhandledPromiseRejectionWarning: TypeError: updateNotification is not a function
    at /usr/local/lib/node_modules/alfred-google-translate/node_modules/alfy/index.js:14:1
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-google-translate/node_modules/alfy/index.js:166:3)
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
(node:7340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7340) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at sM (/usr/local/lib/node_modules/alfred-google-translate/token.js:32:42)
    at /usr/local/lib/node_modules/alfred-google-translate/token.js:111:18
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:59:3)
(node:7340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by xfslove** [comment]
it's seem like the workflow got the wrong Alfy version. 

Did you just installed the alfy with global mode before?  if so you should update the Alfy to 0.9.1 or uninstall it with global mode.

**Comment by Aracki** [comment]
Sorry, but how can I check that? I'm pretty sure I haven't touch `alfy` or any other node module.

**Comment by xfslove** [comment]
the version of alfy is correct, the 'json-parse-better-errors' module is dependent on the 'read-pkg' old version that the alfy dependent.  but I don't know why your local module try to find it, it's expected to find the 'json-parse-even-better-errors'.

could you grep the `parse-json` please?

**Comment by Aracki** [comment]
```
 │ │   ├─┬ parse-json@5.0.0
│ │ │ │   │ ├── parse-json@2.2.0 deduped
│ │ │ │ │ ├─┬ parse-json@2.2.0
│ │   │ ├─┬ parse-json@5.1.0
│ │ │ │   │ ├── parse-json@2.2.0 deduped
│ │ │ │ │ ├─┬ parse-json@2.2.0
│ │   │ ├─┬ parse-json@5.0.0
npm ERR! peer dep missing: eslint@^5.16.0 || ^6.8.0 || ^7.2.0, required by eslint-config-airbnb-base@14.2.0
npm ERR! peer dep missing: eslint-plugin-import@^2.21.2, required by eslint-config-airbnb-base@14.2.0
npm ERR! peer dep missing: eslint-plugin-react-hooks@^1.7.0, required by eslint-config-airbnb@18.0.1
npm ERR! peer dep missing: eslint@^5.16.0 || ^6.8.0 || ^7.2.0, required by eslint-config-airbnb-base@14.2.0
npm ERR! peer dep missing: eslint-plugin-import@^2.21.2, required by eslint-config-airbnb-base@14.2.0
npm ERR! peer dep missing: typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta, required by tsutils@3.17.1
│ │ │ │   │ ├─┬ parse-json@2.2.0
│ │ │ └─┬ parse-json@4.0.0
│ │ │ ├─┬ parse-json@5.1.0
│ │   │ │ │   │   │ ├─┬ parse-json@4.0.0
│ │   ├─┬ parse-json@5.1.0
│ │ │   │ ├─┬ parse-json@4.0.0
│ │ │   │ ├─┬ parse-json@2.2.0
  │ │   │ ├─┬ parse-json@2.2.0
  │   │ ├─┬ parse-json@4.0.0
  │   │   ├─┬ parse-json@5.1.0
```

I'm getting this one ^^. Thanks for trying to solve this @xfslove, but if it's my local npm issue, maybe I can reinstall all the node packages in order to make workflow to work 🤷

**Comment by xfslove** [comment]
thanks for your support. 🙂

I saw the snippet you post, the dependencies is confusion and I can't locate the problem. but it's really look like a package conflict issue. 

maybe need you spend more time with me to locate it, sorry for that.

and as you said Maybe reinstall your local packages is the most simple way, you could have a try.

**Comment by Aracki** [comment]
I've reinstalled node/npm and all of it's packages. Now, the plugin works again! Thanks @xfslove
