### ISSUE TITLE
don't support Alfred4 with error.

### ISSUE THREAD

**Issue by dingcang** [xfslove/alfred-google-translate#76]
```zsh
> alfred-google-translate@2.0.9 postinstall /Users/didi/.nvm/versions/node/v12.13.1/lib/node_modules/alfred-google-translate
> alfy-init

Error: Command failed with exit code 1 (EPERM): alfred-link
    at makeError (/Users/didi/.nvm/versions/node/v12.13.1/lib/node_modules/alfred-google-translate/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/didi/.nvm/versions/node/v12.13.1/lib/node_modules/alfred-google-translate/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/didi/.nvm/versions/node/v12.13.1/lib/node_modules/alfred-google-translate/node_modules/alfy/init.js:7:3 {
  command: 'alfred-link',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr: 'Error: Permission denied to read Alfred preferences at location /Users/didi/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at module.exports (/Users/didi/.nvm/versions/node/v12.13.1/lib/node_modules/alfred-google-translate/node_modules/resolve-alfred-prefs/index.js:44:9)',
  all: 'Error: Permission denied to read Alfred preferences at location /Users/didi/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at module.exports (/Users/didi/.nvm/versions/node/v12.13.1/lib/node_modules/alfred-google-translate/node_modules/resolve-alfred-prefs/index.js:44:9)',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-google-translate@2.0.9 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alfred-google-translate@2.0.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/didi/.npm/_logs/2020-12-28T09_11_34_559Z-debug.log
```
i can't found com.runningwithcrayons.Alfred-Preferences-3.plist in folder /Users/didi/Library/Preferences/. what's wrong

**Comment by xfslove** [comment]
see the logs. `Error: Permission denied`. 

it's permission issue. you could try to install with `sudo` or something else.

**Comment by dingcang** [comment]
> see the logs. `Error: Permission denied`.
> 
> it's permission issue. maybe your node installed with `sudo`. so you could try to install with `sudo` or something else.

i have try to added `sudo` before open this issue, don`t work  too

**Comment by xfslove** [comment]
actually, it's not the workflow issue. 

I'm not sure if it caused by the workflow detected your Alfred version is Alfred 3, so the workflow try to found the `Alfred-Preferences-3.plist` file.

is it possible to try reinstall the Aflred 4? or check your ~/Library directories if it remains Alfred 3 files.
